### ISSUE TITLE
[Request] - do overwatch while I play other games

### ISSUE THREAD

**Issue by fsk35** [BeepIsla/CSGO-Overwatch-Bot#50]
Hi beep, I'm a fan of your overwatch bot, it makes actually possible to get all weekly xp on main account since vertigo boost patch.

Could you please and if possible add a way to do overwatch on the account I am currently playing? Cause I have at least 20 AAA games + 100 or more indies on it and I do nothing while I get my ow count to 20. Can't even do family share.

Thanks.

**Comment by BeepIsla** [comment]
This isn't possible with an external bot like this which logs into your Steam account due to how Steam handles multiple connections to one account.

The best you can do is try Offline Mode on Steam. (Click `Steam` in the top left > Click `Go Offline...`)

---

There is a way to do what you want either by rewriting this in a different language or by using Native Modules both of which I could do but that comes with its own set of challenges, especially to make sure it works cross platform without issues.

**Comment by fsk35** [comment]
Thanks...
